#ifndef COMMON_CONSTANTS_H
#define COMMON_CONSTANTS_H

#define SEND_USERNAME 0x01
#define SEND_INITIAL_MONEY 0x02
#define SEND_CURRENT_CAR 0x03
#define GET_CURRENT_CAR 0x04
#define GET_MARKET_INFO 0x05
#define SEND_MARKET_INFO 0x06
#define BUY_CAR 0x07
#define SEND_CAR_BOUGHT 0x08
#define SEND_ERROR_MESSAGE 0x09

#endif
